### ISSUE TITLE
error running example on linux

### ISSUE THREAD

**Issue by edvail** [IonicaBizau/powershell#3] opened 2016-09-22 12:03 UTC
When I try to run provided example on ubuntu with powershell 6 installed on it i getting following error:
```
{ Error: spawn powershell.exe ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn powershell.exe',
  path: 'powershell.exe',
  spawnargs: [ '-command', '& {Write-Output \'powershell is awesome\'}' ] }
```

**Comment by IonicaBizau** [comment] 2016-09-22 12:08
When I built this that was by design. Currently, it is supposed to run specifically on Windows machines.

If PowerShell is supposed to run now on Linux, this should be fixed as well!

How do you usually run such scripts on Linux machines? :thought_balloon:

**Comment by edvail** [comment] 2016-09-22 12:12
there is just "powershell" command, and "powershell.exe" doesn't exist this is only difference I see for now

**Comment by IonicaBizau** [comment] 2016-09-22 12:14
I'm on it. :rocket:

**Closed** 2016-09-22 12:16 UTC
Labels: bug
